### ISSUE TITLE
angular 4 problem?

### ISSUE THREAD

**Issue by gilior** [500tech/angular-tree-component#274] opened 2017-04-22 09:08 UTC
`**@angular/core@4.0.3**`
`**angular-tree-component@3.3.1**`
ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 78:13 in the original .ts file), resolving symbol action in C:/Users/user/Documents/projects/danel/node_modules/mobx/lib/mobx.d.ts, resolving symbol TreeNodeCollectionComponent in C:/Users/user/Documents/projects/danel/node_modules/angular-tree-component/dist/components/tree-node-collection.component.d.ts

**Comment by jskrzypek** [comment] 2017-04-22 09:42
This is a duplicate of #261 and should be fixed by #267

**Comment by gilior** [comment] 2017-04-22 09:58
ok i downgraded package back  to **3.3.0** now its compiling and running

**Comment by adamkleingit** [comment] 2017-04-29 13:51
@gilior Can you check with 3.4.1? it should solve it

**Closed** 2017-05-20 09:27 UTC
