### ISSUE TITLE
Invalid event name

### ISSUE THREAD

**Issue by cppleon** [500tech/angular-tree-component#379] opened 2017-08-04 08:26 UTC
[lib/constants/events.ts](//github.com/500tech/angular-tree-component/blob/master/lib/constants/events.ts)
```
...
changeFilter: 'changeFilterr',
...
```

**Comment by AlexanderIgorovych** [comment] 2017-08-04 11:10
#375 - quick fix for this issue

**Comment by adamkleingit** [comment] 2017-08-04 15:28
Duplicate of #382

**Closed by adamkleingit** 2017-08-04 15:28 UTC
