### ISSUE TITLE
[Feature] Checkbox support

### ISSUE THREAD

**Issue by DanielCaspers** [500tech/angular-tree-component#427] opened 2017-09-13 16:21 UTC
### Motivation
As mentioned in the [What's next](https://github.com/500tech/angular-tree-component#whats-next) section of the README, Checkbox support would be a beneficial feature for many use cases. 

I have a couple questions that I'd like to ask publicly to see what the future of this feature will be, as I am sure other plugin users are wondering the same. 

**What is in scope vs. out of scope?** 
- [x] Checkbox tied to selection
- [x] Checking/Unchecking of individual nodes, and all nodes through `TreeModel` or `TreeNode` API
- [x] Support for inserting one's own checkbox. Say, [Angular Material's Checkbox](https://material.angular.io/components/checkbox/overview)

**Any idea of when implementation for this might start?**

------

Thank you to all the maintainers for such a mature plugin given how new Angular is as a framework!

**Comment by adamkleingit** [comment] 2017-11-25 14:20
Noted - closing the issue and putting in backlog

**Closed by adamkleingit** 2017-11-25 14:20 UTC
Labels: enhancement

**Comment by guguji5** [comment] 2018-01-25 05:53
I use the checkbox version. 

but the issue is that I can't get the selection you mentioned( Checkbox tied to selection) after users selected. it seems that the TreeModel doesn't apply the api of selection.

**Comment by uurtsaikhb** [comment] 2018-05-11 22:14
@guguji5 

You could do something like this to get all checked nodes ids

```
import {toJS} from 'mobx';

getSelectedNodeIds(selectedLeafNodeIds) {
        const selectedNodes = [];

        Object.entries(toJS(selectedLeafNodeIds)).forEach(([key, value]) => {
            if (value === true) {
                selectedNodes.push(key);
            }
        });

        return selectedNodes;
    }
```

You have to pass `this.tree.treeModel.selectedLeafNodeIds`
