### ISSUE TITLE
changeFilter error

### ISSUE THREAD

**Issue by pmaza** [500tech/angular-tree-component#374] opened 2017-08-02 09:58 UTC
Hi,

There is an error in lib/constants/events.ts .  the event changeFilter: 'changeFilterr' must be changeFilter:'changeFilter'.

**Comment by tantalid** [comment] 2017-08-02 15:23
#375 - quick fix for this issue

**Comment by adamkleingit** [comment] 2017-08-04 15:47
Thanks! Duplicate of #382 
Will be fixed in coming version

**Closed by adamkleingit** 2017-08-04 15:47 UTC
