### ISSUE TITLE
MobX upgrade to 3.0.2 needed to be able to work with ng9

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [500tech/angular-tree-component#765] opened 2019-10-29 18:59 UTC
Angular 9.0 will/is removing Renderer.
MobX has released an upgrade 3.0.2 to remove their dependency on Renderer.
So Angular tree component will have to import the new package to be able to be used with ng 9 I suppose.

Best regards

**Comment by elvisbegovic** [comment] 2019-11-04 08:27
duplicate of https://github.com/500tech/angular-tree-component/issues/762

**Closed** 2020-02-13 15:12 UTC
