### ISSUE TITLE
Cannot read property mouse of undefined

### ISSUE THREAD

**Issue by negue** [500tech/angular-tree-component#198] opened 2017-02-27 23:28 UTC
After clicking on a node I get these error with 3.0.2 & 3.1.0:

`Error in ./TreeNodeComponent class TreeNodeComponent - inline template:16:12 caused by: Cannot read property 'mouse' of undefined`

Just using a normal tree:
`<Tree #tree [nodes]="nodes"></Tree>`

**Comment by adamkleingit** [comment] 2017-03-01 23:44
Hi, I can't reproduce, can you share your repo? Thanks

**Comment by negue** [comment] 2017-03-02 00:01
Just found the error 😄 

in `tree-options.model.ts` I had to change it to:

```ts
  constructor(private options: ITreeOptions = {}) {
    this.actionMapping = defaultsDeep({}, this.options.actionMapping, defaultActionMapping);
  }

```

cause `{}.actionMapping is undefined` and if defaultDeep gets an `undefined` as source, everything else ... stays undefined

**Comment by adamkleingit** [comment] 2017-03-08 08:12
Merged, will be released in the coming version

**Comment by adamkleingit** [comment] 2017-03-08 08:12
Thanks!

**Closed** 2017-03-08 08:11 UTC
