### ISSUE TITLE
Error when expand & collapse are done immediately one after another

### ISSUE THREAD

**Issue by parasjain95** [500tech/angular-tree-component#295] opened 2017-05-08 06:17 UTC
When i press expand collapse arrow without letting one operation complete this error occurs. It occurs once after i start the application and then it works fine and no error is thrown. But whwn i again reload the app and do this again, the error occurs again.

![error](https://cloud.githubusercontent.com/assets/18498327/25792373/d5f633fa-33e3-11e7-9f1a-8e4cb895b9c6.PNG)

**Comment by parasjain95** [comment] 2017-05-08 06:24
If my tree is expanded and then i do collapse and expand immediately, my tree does not show up, however my arrow appears as expanded. This is a big issue. Kindly solve asap.

Secondly How can i change the image for expand collapse? I want it changed in my production build.
Thank you.

**Comment by adamkleingit** [comment] 2017-05-20 09:55
Hi @parasjain95 I cannot reproduce the error, can you try with the latest lib version. If it doesn't work, can you send link to your code?
About the image - you have 2 options:
1. Override `toggle-children-wrapper-expanded`, `toggle-children-wrapper-expanded` and `toggle-children` styles.
2. Supply a custom `treeNodeWrapperTemplate` template and override the expander with your own component

**Comment by parasjain95** [comment] 2017-05-20 15:21
try reproducing this issue with animations on. It will appear

**Comment by adamkleingit** [comment] 2017-05-21 06:29
Reproduced. Will be fixed in 3.7.2

**Closed** 2017-05-21 07:11 UTC
Labels: bug
