### ISSUE TITLE
Not working for angular 7 update

### ISSUE THREAD

**Issue by Kasilingam1230** [500tech/angular-tree-component#694] opened 2018-11-30 07:45 UTC
Documentation in link: https://angular2-tree.readme.io/docs/ doesn't mentioned anything about angular 7 & it doesn't works for angular 7 update. Is there any updates, please reply.

**Comment by adamkleingit** [comment] 2018-12-01 07:33
Duplicate of #689

**Closed by adamkleingit** 2018-12-01 07:33 UTC
