### ISSUE TITLE
scrollIntoView doesn't work properly for some cases

### ISSUE THREAD

**Issue by johnking** [500tech/angular-tree-component#92] opened 2016-10-30 04:39 UTC
@adamkleingit 

Hi there,

I found one issue with the API call - `scrollIntoView`. For my case, it works most time with a small tree, but does not work for the large tree. So I created my own local function based on the `source code` below.

```
TreeNode.prototype.scrollIntoView = function () {
        if (this.elementRef) {
            var nativeElement = this.elementRef.nativeElement;
            nativeElement.scrollIntoViewIfNeeded && nativeElement.scrollIntoViewIfNeeded();
            return this;
        }
    };
```

I am using `scrollIntoView` instead of `scrollIntoViewIfNeeded`, which is also suggested by
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded

My code:

```
        if (this.focusedNode) {
          if (this.focusedNode.elementRef) {
            let nativeElement = this.focusedNode.elementRef.nativeElement;
            nativeElement.scrollIntoView();
          }
        };
```

It works for both small and large trees.

I hope my finding and solution will be helpful to others.

Best

-John

**Comment by denkomanceski** [comment] 2016-12-03 13:01
The best way would be to actually add a boolean to the scrollIntoView function which if true will force to scroll with scrollIntoView(), otherwise use scrollIntoViewIfNeeded.. I also have the same problem.. when I dynamically add a new node and update the tree, I can call focus() and it works fine, but scrollingIntoView doesnt

**Comment by adamkleingit** [comment] 2017-02-03 00:37
Fixed in 2.8.0.
Can you verify?

**Closed** 2017-04-04 07:50 UTC
Labels: bug, Priority

**Comment by johnking** [comment] 2017-09-01 19:36
Hi @adamkleingit, 

  I am using 4.1.0, and it doesn't work in my project, I tried both cases: 
  1. virtualScroll mode and 
  2. non virtualScroll mode

  Since the `elementRef` is not supported any more, my own implementation with it is also broken.

-John

**Comment by johnking** [comment] 2017-09-06 15:41
Hi @adamkleingit,

  We can recover this issue easily either by
  1. limiting the width of tree panel or 
  2. making the display field longer than the width of the tree panel. 

  I even use the `full-tree` example to recover this issue. 

 
<img width="416" alt="screen shot 2017-09-06 at 11 38 04" src="https://user-images.githubusercontent.com/1787137/30120830-f9b7bc28-92f7-11e7-9445-55d64f21cad5.png">

I hope my findings can help you to fix the issue. 

thanks

-John

**Comment by ottosson** [comment] 2018-02-11 10:00
I've got the same issue. scrollIntoView works in Firefox and IE11 for my application, but not in Chrome.
I can't seem to reproduce a working example to show here though.

Here is a [broken example](https://angular-tree-component-scrollintoview-bug.stackblitz.io) where scrollIntoView doesn't work in any browser I've tried with.

**Comment by phoude** [comment] 2018-05-11 03:08
Having same issue as ottoson. scrollIntoView does not scroll to my node with Chrome

**Comment by adamkleingit** [comment] 2018-05-11 18:06
This is not a chrome problem (in the latest version), it happens because currently scrolling into view only works if the tree itself is rendered within a container that is limited in height and has overflow hidden. This is because the scrolling happens inside a viewport element that is part of the tree. If the scroller is on an external element then this will (currently) not work.

The solution I will implement is to add a `scrollContainer` option that will allow you to specify which scrollContainer. Will publish in coming version and update docs

**Comment by adamkleingit** [comment] 2018-05-11 18:09
Published 7.2.0

**Comment by phoude** [comment] 2018-06-07 01:40
Hi, I might not understand how the scrollContainer is supposed to be set but here is an example where I can't get scrollIntoView to work: https://stackblitz.com/edit/angular-twwypu?file=src%2Fapp%2Fscroll-container.component.ts

**Comment by phoude** [comment] 2018-08-07 19:52
I don't see how this issue is resolved. Check my non-working example in my last post.

**Comment by adamkleingit** [comment] 2018-08-12 08:30
Hi,
You have 2 options:  
1) Give a fixed height and `overflow: auto` to the `scrollcontainer` element.

2) Set:
```
// css:
html {
  height: 100%;
  overflow: auto;
}

// ts:
options = {
  scrollContainer: document.documentElement
}
```
https://angular-cds4dx.stackblitz.io

Can you try?

**Comment by phoude** [comment] 2018-08-13 19:44
It did the trick. Thanks!
